  language: "ru"

  pipeline:
  - name: SpacyNLP
    model: "ru_core_news_md"
  - name: SpacyTokenizer
  - name: SpacyEntityExtractor
  - name: SpacyFeaturizer
    pooling: mean
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: "EmbeddingIntentClassifier"
    epochs: 130

  policies:
    - name: MemoizationPolicy
    - name: KerasPolicy
    - name: MappingPolicy